"""
Disclaimer Enforcer Module

Ensures all legal outputs include appropriate disclaimers and warnings.
Prevents system from providing outputs without proper legal disclaimers.
"""

from typing import Dict, List, Optional
from datetime import datetime
from src.utils import get_logger

logger = get_logger(__name__)


class DisclaimerEnforcer:
    """
    Enforce legal disclaimers on all system outputs.

    Ensures users understand that outputs are for informational purposes
    only and do not constitute legal advice.
    """

    # Standard disclaimer templates
    STANDARD_DISCLAIMER = (
        "DISCLAIMER: This information is for educational and informational purposes only. "
        "It does NOT constitute legal advice. Laws and regulations are subject to change, "
        "and the application of law can vary based on specific facts. "
        "Always consult a qualified legal practitioner for advice on your specific situation."
    )

    LOW_CONFIDENCE_DISCLAIMER = (
        "CAUTION: This response has low confidence. The information may be incomplete or uncertain. "
        "It is strongly recommended to consult a qualified legal practitioner before taking any action."
    )

    CONFLICT_DISCLAIMER = (
        "WARNING: Conflicting legal provisions have been detected. "
        "The application of law in this situation may be ambiguous or contested. "
        "Professional legal advice is essential to navigate these conflicts."
    )

    LIMITATION_DISCLAIMER = (
        "NOTE: This response is based on available information in the system's knowledge base, "
        "which may be incomplete or outdated. Cross-reference with official legal sources "
        "and consult a legal professional for comprehensive guidance."
    )

    AI_SYSTEM_DISCLAIMER = (
        "AI SYSTEM NOTICE: This response was generated by an AI system. "
        "While efforts are made to ensure accuracy, the system may make errors. "
        "Verify all information with authoritative legal sources."
    )

    def __init__(
        self,
        enforce_strict: bool = True,
        include_timestamp: bool = True
    ):
        """
        Initialize disclaimer enforcer.

        Args:
            enforce_strict: If True, raises error if disclaimers missing
            include_timestamp: If True, adds timestamp to disclaimers
        """
        self.enforce_strict = enforce_strict
        self.include_timestamp = include_timestamp
        logger.info("DisclaimerEnforcer initialized")

    def enforce_disclaimers(
        self,
        answer: str,
        confidence_result: Optional[Dict] = None,
        inference_result: Optional[Dict] = None,
        verification_result: Optional[Dict] = None
    ) -> Dict:
        """
        Enforce disclaimers on legal answer.

        Args:
            answer: Generated answer text
            confidence_result: Confidence scoring results
            inference_result: Inference engine results
            verification_result: Verification results

        Returns:
            Dictionary with answer and disclaimers
        """
        logger.info("Enforcing disclaimers on answer")

        # Collect required disclaimers
        disclaimers = self._collect_required_disclaimers(
            answer,
            confidence_result,
            inference_result,
            verification_result
        )

        # Check if answer already has disclaimers
        has_disclaimers = self._check_existing_disclaimers(answer)

        # Format disclaimers
        formatted_disclaimers = self._format_disclaimers(disclaimers)

        # Generate final output
        if has_disclaimers:
            logger.info("Answer already contains disclaimers")
            final_answer = answer
        else:
            logger.info(f"Adding {len(disclaimers)} disclaimers to answer")
            final_answer = self._append_disclaimers(answer, formatted_disclaimers)

        return {
            'answer_with_disclaimers': final_answer,
            'disclaimers': disclaimers,
            'formatted_disclaimers': formatted_disclaimers,
            'had_existing_disclaimers': has_disclaimers,
            'disclaimer_count': len(disclaimers),
            'is_compliant': True
        }

    def _collect_required_disclaimers(
        self,
        answer: str,
        confidence_result: Optional[Dict],
        inference_result: Optional[Dict],
        verification_result: Optional[Dict]
    ) -> List[Dict]:
        """
        Collect all required disclaimers based on context.

        Args:
            answer: Answer text
            confidence_result: Confidence results
            inference_result: Inference results
            verification_result: Verification results

        Returns:
            List of disclaimer dictionaries
        """
        disclaimers = []

        # 1. Always include standard disclaimer
        disclaimers.append({
            'type': 'standard',
            'severity': 'critical',
            'text': self.STANDARD_DISCLAIMER,
            'required': True
        })

        # 2. Always include AI system disclaimer
        disclaimers.append({
            'type': 'ai_system',
            'severity': 'high',
            'text': self.AI_SYSTEM_DISCLAIMER,
            'required': True
        })

        # 3. Low confidence disclaimer
        if confidence_result:
            confidence = confidence_result.get('aggregate_confidence', 1.0)
            if confidence < 0.6:
                disclaimers.append({
                    'type': 'low_confidence',
                    'severity': 'high',
                    'text': self.LOW_CONFIDENCE_DISCLAIMER,
                    'required': True,
                    'confidence_score': confidence
                })

        # 4. Conflict disclaimer
        if inference_result and inference_result.get('has_conflicts'):
            disclaimers.append({
                'type': 'conflict',
                'severity': 'critical',
                'text': self.CONFLICT_DISCLAIMER,
                'required': True,
                'num_conflicts': len(inference_result.get('conflicts', []))
            })

        # 5. Limitation disclaimer
        if verification_result:
            faithfulness = verification_result.get('faithfulness', {})
            if faithfulness.get('faithfulness_score', 1.0) < 0.7:
                disclaimers.append({
                    'type': 'limitation',
                    'severity': 'medium',
                    'text': self.LIMITATION_DISCLAIMER,
                    'required': True
                })

        # 6. Timestamp (if enabled)
        if self.include_timestamp:
            timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            disclaimers.append({
                'type': 'timestamp',
                'severity': 'info',
                'text': f"Generated on: {timestamp}",
                'required': False
            })

        return disclaimers

    def _check_existing_disclaimers(self, answer: str) -> bool:
        """
        Check if answer already contains disclaimers.

        Args:
            answer: Answer text

        Returns:
            True if disclaimers found, False otherwise
        """
        disclaimer_keywords = [
            'disclaimer',
            'not constitute legal advice',
            'consult a qualified',
            'for informational purposes',
            'ai system'
        ]

        answer_lower = answer.lower()
        for keyword in disclaimer_keywords:
            if keyword in answer_lower:
                return True

        return False

    def _format_disclaimers(self, disclaimers: List[Dict]) -> str:
        """
        Format disclaimers for display.

        Args:
            disclaimers: List of disclaimer dictionaries

        Returns:
            Formatted disclaimer text
        """
        formatted = "\n\n" + "=" * 80 + "\n"
        formatted += "IMPORTANT LEGAL NOTICES\n"
        formatted += "=" * 80 + "\n\n"

        # Group by severity
        critical = [d for d in disclaimers if d['severity'] == 'critical']
        high = [d for d in disclaimers if d['severity'] == 'high']
        medium = [d for d in disclaimers if d['severity'] == 'medium']
        info = [d for d in disclaimers if d['severity'] == 'info']

        # Add critical disclaimers first
        for disclaimer in critical:
            formatted += f"⚠️  {disclaimer['text']}\n\n"

        # Add high severity disclaimers
        for disclaimer in high:
            formatted += f"⚠️  {disclaimer['text']}\n\n"

        # Add medium severity disclaimers
        for disclaimer in medium:
            formatted += f"ℹ️  {disclaimer['text']}\n\n"

        # Add info disclaimers
        for disclaimer in info:
            formatted += f"{disclaimer['text']}\n\n"

        formatted += "=" * 80 + "\n"

        return formatted

    def _append_disclaimers(self, answer: str, formatted_disclaimers: str) -> str:
        """
        Append disclaimers to answer.

        Args:
            answer: Original answer
            formatted_disclaimers: Formatted disclaimers

        Returns:
            Answer with disclaimers appended
        """
        return answer + formatted_disclaimers

    def validate_compliance(self, output: Dict) -> bool:
        """
        Validate that output is compliant with disclaimer requirements.

        Args:
            output: Output dictionary from enforce_disclaimers()

        Returns:
            True if compliant, False otherwise
        """
        # Check that all required disclaimers are present
        disclaimers = output.get('disclaimers', [])
        required_disclaimers = [d for d in disclaimers if d.get('required', False)]

        if not required_disclaimers:
            logger.error("No required disclaimers found")
            return False

        # Check that answer contains disclaimer text
        answer = output.get('answer_with_disclaimers', '')
        if not self._check_existing_disclaimers(answer):
            logger.error("Answer does not contain disclaimers")
            return False

        logger.info("Disclaimer compliance validated")
        return True

    def get_minimal_disclaimer(self) -> str:
        """
        Get minimal disclaimer for short outputs.

        Returns:
            Minimal disclaimer text
        """
        return (
            "⚠️  NOT LEGAL ADVICE: This is for information only. "
            "Consult a qualified legal practitioner."
        )

    def create_custom_disclaimer(
        self,
        disclaimer_text: str,
        severity: str = 'high',
        disclaimer_type: str = 'custom'
    ) -> Dict:
        """
        Create a custom disclaimer.

        Args:
            disclaimer_text: Disclaimer text
            severity: Severity level (critical, high, medium, info)
            disclaimer_type: Type identifier

        Returns:
            Disclaimer dictionary
        """
        return {
            'type': disclaimer_type,
            'severity': severity,
            'text': disclaimer_text,
            'required': True
        }

    def get_sri_lankan_specific_disclaimer(self) -> str:
        """
        Get Sri Lankan law-specific disclaimer.

        Returns:
            Sri Lankan specific disclaimer text
        """
        return (
            "SRI LANKAN LAW NOTICE: This system provides information about Sri Lankan law. "
            "Laws may have been amended since the system's knowledge was last updated. "
            "Always verify current law with official sources (Attorney General's Department, "
            "Parliament of Sri Lanka) and consult a Sri Lankan legal practitioner "
            "registered with the Supreme Court."
        )

    def add_jurisdictional_disclaimer(
        self,
        jurisdiction: str = "Sri Lanka"
    ) -> Dict:
        """
        Add jurisdiction-specific disclaimer.

        Args:
            jurisdiction: Legal jurisdiction

        Returns:
            Disclaimer dictionary
        """
        text = (
            f"JURISDICTIONAL NOTICE: This information pertains to {jurisdiction} law. "
            f"It may not be applicable in other jurisdictions. Legal systems vary significantly, "
            f"and laws change over time. Always consult local legal experts."
        )

        return {
            'type': 'jurisdictional',
            'severity': 'high',
            'text': text,
            'required': True,
            'jurisdiction': jurisdiction
        }
